export const PROCESSED_DATA_ACTIONS = {
  FETCH_PROCESSED_DATA: "FETCH_PROCESSED_DATA",
  PROCESSED_DATA_FETCH_SUCCESS: "PROCESSED_DATA_FETCH_SUCCESS",
  PROCESSED_DATA_FETCH_ON_HOLD: "PROCESSED_DATA_ON_HOLD",
  PROCESSED_DATA_FETCH_FAILED: "PROCESSED_DATA_FETCH_FAILED",
};
