export const COMMON_DATA_ACTIONS = {
  FETCH_COMMON_DATA: "FETCH_COMMON_DATA",
  COMMON_DATA_FETCH_SUCCESS: "COMMON_DATA_FETCH_SUCCESS",
  COMMON_DATA_FETCH_ON_HOLD: "COMMON_DATA_ON_HOLD",
  COMMON_DATA_FETCH_FAILED: "COMMON_DATA_FETCH_FAILED",
};
