export const RENTAL_DISTRIBUTION_DURATION_CHART_DATA_ACTIONS = {
  FETCH_RENTAL_DISTRIBUTION_DURATION_CHART_DATA:
    "FETCH_RENTAL_DISTRIBUTION_DURATION_CHART_DATA",
  RENTAL_DISTRIBUTION_DURATION_CHART_DATA_FETCH_SUCCESS:
    "RENTAL_DISTRIBUTION_DURATION_CHART_DATA_FETCH_SUCCESS",
  RENTAL_DISTRIBUTION_DURATION_CHART_DATA_FETCH_ON_HOLD:
    "RENTAL_DISTRIBUTION_DURATION_CHART_DATA_ON_HOLD",
  RENTAL_DISTRIBUTION_DURATION_CHART_DATA_FETCH_FAILED:
    "RENTAL_DISTRIBUTION_DURATION_CHART_DATA_FETCH_FAILED",
};
