export const DOWNLOAD_FILE_ACTIONS = {
  DOWNLOAD_FILE_SUCCESS: "DOWNLOAD_FILE_SUCCESS",
  DOWNLOAD_FILE_ON_HOLD: "DOWNLOAD_FILE_ON_HOLD",
  DOWNLOAD_FILE_FAILED: "DOWNLOAD_FILE_FAILED",
  DOWNLOAD_FILE_RESET: "DOWNLOAD_FILE_RESET",
};
