export const POPUALR_STATIONS_CHART_DATA_ACTIONS = {
  FETCH_POPUALR_STATIONS_CHART_DATA: "FETCH_POPUALR_STATIONS_CHART_DATA",
  POPUALR_STATIONS_CHART_DATA_FETCH_SUCCESS:
    "POPUALR_STATIONS_CHART_DATA_FETCH_SUCCESS",
  POPUALR_STATIONS_CHART_DATA_FETCH_ON_HOLD:
    "POPUALR_STATIONS_CHART_DATA_ON_HOLD",
  POPUALR_STATIONS_CHART_DATA_FETCH_FAILED:
    "POPUALR_STATIONS_CHART_DATA_FETCH_FAILED",
};
