export const STATIONS_DISTANCE_CHART_DATA_ACTIONS = {
  FETCH_STATIONS_DISTANCE_CHART_DATA: "FETCH_STATIONS_DISTANCE_CHART_DATA",
  STATIONS_DISTANCE_CHART_DATA_FETCH_SUCCESS:
    "STATIONS_DISTANCE_CHART_DATA_FETCH_SUCCESS",
  STATIONS_DISTANCE_CHART_DATA_FETCH_ON_HOLD:
    "STATIONS_DISTANCE_CHART_DATA_ON_HOLD",
  STATIONS_DISTANCE_CHART_DATA_FETCH_FAILED:
    "STATIONS_DISTANCE_CHART_DATA_FETCH_FAILED",
};
