export const STATIONS_MAP_CHART_DATA_ACTIONS = {
  FETCH_STATIONS_MAP_CHART_DATA: "FETCH_STATIONS_MAP_CHART_DATA",
  STATIONS_MAP_CHART_DATA_FETCH_SUCCESS:
    "STATIONS_MAP_CHART_DATA_FETCH_SUCCESS",
  STATIONS_MAP_CHART_DATA_FETCH_ON_HOLD: "STATIONS_MAP_CHART_DATA_ON_HOLD",
  STATIONS_MAP_CHART_DATA_FETCH_FAILED: "STATIONS_MAP_CHART_DATA_FETCH_FAILED",
};
