export const UPLOAD_FILE_ACTIONS = {
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_ON_HOLD: "UPLOAD_FILE_ON_HOLD",
  UPLOAD_FILE_FAILED: "UPLOAD_FILE_FAILED",
  UPLOAD_FILE_RESET: "UPLOAD_FILE_RESET",
};
