const UPLOAD_FLEET_SERVICES_FILE = "/upload-file/";
const DOWNLOAD_FLEET_SERVICES_FILE = "/download-file/";
const FLEET_SERVICES_PROCESSED_DATA = "/processed-data/";
const DATA_SETS_LIST = "/dataset-list/";
const POPULAR_STATIONS_CHART_DATA = "/popular-stations/";
const STATIONS_TURNOVER_CHART_DATA = "/stations-most-turnover/";
const RENTAL_DISTRIBUTION_DURATION_CHART_DATA = "/rental-distribution/";
const STATIONS_MAP_CHART_DATA = "/stations-map-data/";
const STATIONS_DISTANCE_CHART_DATA = "/stations-distance-data/";

const urlConstants = {
  UPLOAD_FLEET_SERVICES_FILE: `${UPLOAD_FLEET_SERVICES_FILE}`,
  DOWNLOAD_FLEET_SERVICES_FILE: `${DOWNLOAD_FLEET_SERVICES_FILE}`,
  FLEET_SERVICES_PROCESSED_DATA: `${FLEET_SERVICES_PROCESSED_DATA}`,
  DATA_SETS_LIST: `${DATA_SETS_LIST}`,
  POPULAR_STATIONS_CHART_DATA: `${POPULAR_STATIONS_CHART_DATA}`,
  STATIONS_TURNOVER_CHART_DATA: `${STATIONS_TURNOVER_CHART_DATA}`,
  RENTAL_DISTRIBUTION_DURATION_CHART_DATA: `${RENTAL_DISTRIBUTION_DURATION_CHART_DATA}`,
  STATIONS_MAP_CHART_DATA: `${STATIONS_MAP_CHART_DATA}`,
  STATIONS_DISTANCE_CHART_DATA: `${STATIONS_DISTANCE_CHART_DATA}`,
};

export default urlConstants;
