const UPLOAD_FLEET_SERVICES_FILE = "/upload-file/";
const DOWNLOAD_FLEET_SERVICES_FILE = "/download-file/";
const FLEET_SERVICES_PROCESSED_DATA = "/processed-data/";

const urlConstants = {
  UPLOAD_FLEET_SERVICES_FILE: `${UPLOAD_FLEET_SERVICES_FILE}`,
  DOWNLOAD_FLEET_SERVICES_FILE: `${DOWNLOAD_FLEET_SERVICES_FILE}`,
  FLEET_SERVICES_PROCESSED_DATA: `${FLEET_SERVICES_PROCESSED_DATA}`,
};

export default urlConstants;
