export const GET_CALENDARS_DATA = 'GET_CALENDARS_DATA';
export const GET_REF_CALENDARS_DATA = 'GET_REF_CALENDARS_DATA';
export const GET_DETAILED_DATA = 'GET_DETAILED_DATA';
export const GET_CAMPAIGN_MATRIX = 'GET_CAMPAIGN_MATRIX';
export const GET_PRODUCTS = 'GET_PRODUCTS';
